### ISSUE TITLE
Breve descripcion de funcionamiento

### ISSUE THREAD

**Issue by richiprieto** [pythonecuador/pylearn#15]
Saludos,
Creo que la descripción esta muy bien pero sería chévere que se indique como usar el repo.

**Comment by stsewd** [comment]
Aún no hay nada :D jaja

**Comment by Seburath** [comment]
Lo mas cercano es lo que esta en el README, caracteristicas y no caracteristicas.

**Comment by richiprieto** [comment]
Rayos, pues creo que debemos trabajar en eso, expliquen como va para dar una manito.

**Comment by stsewd** [comment]
o sea, aún no hay código, en eso estamos
